server:
  port: 9020

spring:
  application:
    name: CORE-BANKING-SERVICE
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:9296}

  ## keycloak configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${RESOURCE_SERVER_URI:http://localhost:9091/realms/sbilh}